# Generated by Django 3.2.13 on 2022-05-29 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userphonenumber', models.CharField(blank=True, help_text='Your phone number', max_length=20, null=True, unique=True)),
                ('useraddress', models.CharField(blank=True, help_text='Your address', max_length=20, null=True, unique=True)),
                ('user', models.OneToOneField(max_length=300, on_delete=django.db.models.deletion.CASCADE, related_name='surveyor', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
