# Generated by Django 3.2.13 on 2022-05-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('labour_per_day', models.IntegerField(blank=True, default=0, null=True)),
                ('artisan_per_day', models.IntegerField(blank=True, default=0, null=True)),
                ('cal_DB_per_day', models.IntegerField(blank=True, default=0, null=True)),
                ('diesel_price_per_liter', models.IntegerField(blank=True, default=0, null=True)),
                ('petrol_price_per_liter', models.IntegerField(blank=True, default=0, null=True)),
                ('extractor_per_day', models.IntegerField(blank=True, default=0, null=True)),
                ('dieldrex_per_liter', models.IntegerField(blank=True, default=0, null=True)),
                ('laterite_per_m3', models.IntegerField(blank=True, default=0, null=True)),
                ('hand_roller_per_day', models.IntegerField(blank=True, default=0, null=True)),
                ('hardcore_per_m3', models.IntegerField(blank=True, default=0, help_text='broken blks', null=True)),
                ('tipper_per_day', models.IntegerField(blank=True, default=0, help_text='3.82m3', null=True)),
                ('polythene_per_roll', models.IntegerField(blank=True, default=0, null=True)),
                ('cement_per_bag', models.IntegerField(blank=True, default=0, null=True)),
                ('sharp_sand_per_m3', models.IntegerField(blank=True, default=0, null=True)),
                ('so_sand_per_m3', models.IntegerField(blank=True, default=0, null=True)),
                ('granite_per_m3', models.IntegerField(blank=True, default=0, null=True)),
                ('mixer_poker_operator_per_day', models.IntegerField(blank=True, default=0, null=True)),
                ('HT_bars_per_ton', models.IntegerField(blank=True, default=0, null=True)),
                ('MS_bars_per_ton', models.IntegerField(blank=True, default=0, null=True)),
                ('binding_wire_per_kg', models.IntegerField(blank=True, default=0, null=True)),
                ('BRC_65', models.IntegerField(blank=True, default=0, null=True)),
                ('A142_per_m2', models.IntegerField(blank=True, default=0, null=True)),
                ('record_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
